name: ci

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build and run tests
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm i
        npm run setup
        npm run build

        npx ganache-cli &
        npm test

    - name: Lint
      run: npm run lint
