name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm i
      - run: npm run setup
      - run: npm run build

      - run: npx ganache-cli &
      - run: npm test

      - name: Check Linter bugs
        run: npm run lint

      - name: Fix Linter bugs
        run: npm run lint:fix

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
